Django/alternate (CBV design)/Django/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('blog.urls')),
)

# On active maintenant le service des fichiers statiques par Django
# mais uniquement en mode DEBUG (pour éviter de l'oublier en prod)
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'%s/(?P<path>.*)$' % settings.MEDIA_URL.strip('/'),
         'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

Django/alternate (CBV design)/blog/urls.py
from django.conf.urls import patterns, include, url
from blog.views import ListHomePosts, PostDetails, ListPostsByCategory, ListPostsByUser, comment

urlpatterns = patterns('blog.views',
	url(r'^$', ListHomePosts.as_view(), name="home"),
	url(r'^(?P<slug>[-\w]+)/$', PostDetails.as_view(), name="post_details"),
	url(r'^category/(?P<slug>[-\w]+)/$', ListPostsByCategory.as_view(), name="post_category"),
	url(r'^author/(?P<id>[-\d]+)/$', ListPostsByUser.as_view(), name="post_user"),
	url(r'^comment/(?P<post_id>[-\d]+)/$', comment, name="comment"),
)

Django/alternate (CBV design)/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

class Category(models.Model):
	""" Model Category """
	name = models.CharField('Name', max_length=255, blank=False)
	slug = models.SlugField(blank=False, max_length=255, db_index= True, unique=True)

	def __unicode__(self):
		return self.name


class Post(models.Model):
	""" Model Post """
	title    = models.CharField('Title', max_length=255, blank=False)
	content  = models.TextField(verbose_name=u'Content')
	slug     = models.SlugField(blank=False, max_length=255, db_index= True, unique=True)
	date     = models.DateField(auto_now_add=False, auto_now=False, blank=True, verbose_name='Date')
	category = models.ForeignKey(Category, blank = True, null = True)
	user     = models.ForeignKey(User, blank = True, null = True)

	def __unicode__(self):
		return self.title

	class Meta:
		ordering = ['-date']

class Comment(models.Model):
	""" Model Comment """
	post     = models.ForeignKey(Post,  blank = False, null = False)
	username = models.CharField(max_length=90, blank = False, null = False )
	mail     = models.EmailField(blank = False, null = False)
	message  = models.TextField(blank = False, null = False)
	created  = models.DateTimeField(auto_now=True, auto_now_add=True, blank = False, null = False)

	def __unicode__(self):
		return self.post.title + " - " + self.username

Django/alternate (CBV design)/blog/forms.py
#-*- coding: utf-8 -*-
from django.forms import ModelForm
from blog.models import Comment

class CommentForm(ModelForm):
	class Meta:
		model = Comment

Django/alternate (CBV design)/blog/views.py
from blog.models import Post, Comment
from django.views.generic import ListView, DetailView
from blog.forms import CommentForm
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

class ListHomePosts(ListView):
	model               = Post
	context_object_name = "posts"
	template_name       = "blog/home.html"
	paginate_by         = 5

	def get_context_data(self, **kwargs):
		context = super(ListHomePosts, self).get_context_data(**kwargs)
		context['header']    = 'Blog'
		context['subheader'] = 'Welcome on my blog'
		return context

class ListPostsByCategory(ListView):
	model               = Post
	context_object_name = "posts"
	template_name       = "blog/home.html"
	paginate_by         = 5

	def get_queryset(self):
		return Post.objects.filter(category__slug=self.kwargs['slug'])

class ListPostsByUser(ListView):
	model               = Post
	context_object_name = "posts"
	template_name       = "blog/home.html"
	paginate_by         = 5

	def get_queryset(self):
		return Post.objects.filter(user__id=self.kwargs['id'])

class PostDetails(DetailView):
	model               = Post
	context_object_name = "post"
	template_name       = "blog/post_details.html"

def comment(request, post_id):
	if request.method == 'POST':
		post_obj = Post.objects.get(id = post_id)
		mail     = request.POST.get('mail')
		username = request.POST.get('username')
		message  = request.POST.get('message')
		post     = request.POST.get('post', post_id)

		data = {
			'mail'     : mail,
			'username' : username,
			'message'  : message,
			'post'     : post_id
		}

		form = CommentForm(data)

		if form.is_valid():
			comment = Comment(mail= mail, username=username, message=message, post=post_obj)
			comment.save()
			request.session['comment_error']   = False
			request.session['comment_success'] = True
		else:
			request.session['comment_success'] = False
			request.session['comment_error']   = True
	else:
		form = CommentForm()

	return HttpResponseRedirect(reverse('post_details', kwargs={'slug': post_obj.slug}))

Django/alternate (CBV design)/blog/templates/blog/categories.html
<h4>Categories</h4>
{% if categories %}
    <div class="list-group">
        {% for category in categories %}
         <a href="{% url "post_category" category.slug %}" class="list-group-item">
         <span class="badge">{{category.post_set.all|length}}</span>
            {{category.name}}
        </a>
    </a>
        {% endfor %}
    </div>
{% else %}
<h5>There are not categories</h5>
{% endif %}

Django/alternate (CBV design)/blog/templates/blog/home.html
{% extends "blog/layout.html" %}
{% load markup %}
{% block content %}
<div class="page-header">
  {% if header %}
    <h1>{{header}}</h1>
  {% endif %}
  {% if subheader %}
    <p class="lead">{{subheader}}</p>
  {% endif %}
</div>
{% if posts %}
  {% for post in posts %}
      <article>
         <h2><a href="{% url "post_details" post.slug %}">{{ post.title}}</a></h2>
         <p>{{ post.content|markdown|truncatewords_html:50 }}</p>
         <p class="text-right"><a href="{% url "post_details" post.slug %}" class="btn btn-primary">Read more...</a>
      </article>
      <hr>
  {% endfor %}
{% else %}
  <h2>There are no post</h2>
{% endif %}
 
{% if is_paginated %}
    <ul class="pagination">
       {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}">« </a></li>
       {% endif %}
       {% if page_obj.paginator.page_range %}
            {% for num in page_obj.paginator.page_range %}
                {% ifequal num page_obj.number %}
                    <li><span>{{ num }}</span></li>
                {% else %}
                    <li><a href="?page={{num}}">{{ num }}</a></li>
                {% endifequal %}
            {% endfor %}
          </li>
       {% endif %}
       {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}"> »</a></li>
       {% endif %}
    </ul>
{% endif %}
{% endblock %}

Django/alternate (CBV design)/blog/templates/blog/latest_posts.html
<h4>Last posts</h4>
{% if posts %}
    <div class="list-group">
        {% for post in posts %}
         <a href="{% url "post_details" post.slug %}" class="list-group-item">
            {{post.title}}
        </a>
        {% endfor %}
        </div>
    </div>
{% else %}
<h5>There are not post</h5>

{% endif %}

Django/alternate (CBV design)/blog/templates/blog/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>{% block title %} Blog {% endblock %} | MyDomain.com</title>

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
        <style>
            body {
                padding-top: 50px;
            }
            .sidebar{
                margin-top: 50px;
            }
        </style>
    </head>

    <body>

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Blog</a>
                </div>

                <div class="collapse navbar-collapse navbar-ex1-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li><a href="/admin">Admin</a></li>
                    </ul>
                </div>

            </div><!-- /.container -->
        </div>

        <div class="container">

            <div class="row">
                <div class="col-md-8">
                    {% block content %}{% endblock %}
                </div>

                <div class="col-md-4 sidebar">
                    {% include "blog/sidebar.html" %}
                </div>
            </div>
        </div><!-- /.container -->

    </body>
</html>

Django/alternate (CBV design)/blog/templates/blog/post_details.html
{% extends "blog/layout.html" %}
{% load markup %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
	{% if post %}
		<div class="page-header">
			<h1>{{ post.title }}</h1>
			<p><small>
				Category : <a href="{% url "post_category" post.category.slug %}">{{post.category.name}}</a>,
				by <a href="{% url "post_user" post.user.id %}">{{post.user.username}}</a> on <em> {{ post.date|date:"M d Y" }}</em>
			</small></p>
		</div>
		{{ post.content|markdown }}
		<hr />
		<section class="comments">
		<h3>Comment this post</h3>
        {% if request.session.comment_error %} <div class="alert alert-danger"><strong>Oh snap !</strong> you did some errors</div> {% endif %}
        {% if request.session.comment_success %} <div class="alert alert-success"> Your comment has been save </div> {% endif %}
		<form action="{% url "comment" post.id %}" method="post" role="form">
        {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                    {{form.errors}}
                    <input type="email" name="mail" class="form-control" placeholder="Your email" />
                    {{form.mail.error}}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="text" name="username" class="form-control" id="exampleInputEmail1" placeholder="Your username">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <textarea class="form-control" name="message" rows="3" placeholder="Your comment"></textarea>
            </div>
            <div class="form-group">
                <button type="submit" value="Post" class="btn btn-primary">Submit</button>
            </div>
        </form>
        <h3> {{ post.comment_set.all|length }} Commentaire(s)</h3>
        {% for comment in post.comment_set.all %}
        <div class="row">
            <div class="col-md-2">
                <img src="http://lorempicsum.com/futurama/100/100/4" width="100%">
            </div>
            <div class="col-md-10">
                <p><strong>{{comment.username}}</strong> {{comment.created|timesince}} ago</p>
                <p>{{comment.message}}</p>
            </div>
        </div>
        {% endfor %}
		</section>
	{% endif %}
{% endblock %}

Django/alternate (CBV design)/blog/templates/blog/sidebar.html
{% block sidebar %}
	{% load cache %}
	{% cache 3600 sidebar %}
    	{% load sidebar %}
    	{% categories %}
    	{% latest_posts %}
    {% endcache %}
{% endblock %}