Rails4/Amilti/config/routes.rb
Rails4Alternate::Application.routes.draw do
  devise_for :users
  root 'home/posts#index'

  scope module: 'home' do
    get 'category/:id' => 'posts#category', as: :category
    get 'author/:id' => 'posts#author', as: :author
    resources :posts, :only => [:index, :show]
    resources :comments, :only => [:create]

  end
  namespace :admin do
    resources :posts
  end

  

end

Rails4/Amilti/app/models/category.rb
class Category < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: :slugged
	has_many :posts
end

Rails4/Amilti/app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :mail, email_format: { message: "doesn't look like an email address" }
	validates :username, :content, presence: true
	belongs_to :post
end

Rails4/Amilti/app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	before_save :to_slug
	friendly_id :name, use: :slugged

	validates :name, :content, presence: true
	has_many :comments
	belongs_to :category, :counter_cache => true
	belongs_to :user

	def should_generate_new_friendly_id?
		slug.blank?
	end

	def to_slug
		unless self.slug.blank?
			 self.slug = self.slug.downcase.gsub(" ", "-")
		end
	end
end

Rails4/Amilti/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
         
	has_many :posts

end

Rails4/Amilti/app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base
	layout 'admin'
	before_filter :authenticate_user!

end

Rails4/Amilti/app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController

	def index
		@posts = Post.order('created_at DESC').page(params[:page]).per(5)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
      	if @post.save
			flash[:message] = "Post was successfully created."
			redirect_to admin_posts_path
      	else
			render action: 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.friendly.find(params[:id])
		@post.update_attributes(post_params)
		if @post.save
			redirect_to admin_posts_path
		else
			render action: 'edit'
		end
	end

	def destroy
		post = Post.find(params[:id])
		post.destroy
		redirect_to :back
	end

	private
    	def post_params
    		if current_user
				params.require(:post).permit!
			end
		end
	
end

Rails4/Amilti/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rails4/Amilti/app/controllers/home/comments_controller.rb
class Home::CommentsController < Home::HomeController
	def create
		@comment = Comment.new(comment_params)
		@post = Post.find(params[:comment][:post_id])
		if @comment.save
			flash[:message] = "Post was successfully created."
			redirect_to @comment.post
		else
			render 'home/posts/show'
		end
	end

	private
	
    def comment_params
    	if current_user
			params.require(:comment).permit!
		end
	end
	

end

Rails4/Amilti/app/controllers/home/home_controller.rb
class Home::HomeController < ActionController::Base
	layout 'application'
	before_filter :categories, :latest_post

	def categories
		@categories = Category.all
	end

	def latest_post
		@latest_post = Post.order('created_at DESC').limit(2)
	end
end

Rails4/Amilti/app/controllers/home/posts_controller.rb
class Home::PostsController < Home::HomeController

	def index
		@posts = Post.order('created_at DESC').page(params[:page]).per(5)
	end

	def show
		@post = Post.friendly.find(params[:id])
	end

	def category
		@category = Category.friendly.find(params[:id])
		@posts = @category.posts.page(params[:page]).per(5)
	end

	def author
		@author = User.find(params[:id])
		@posts = @author.posts.page(params[:page]).per(5)
	end

end

Rails4/Amilti/app/helpers/application_helper.rb
module ApplicationHelper
	def namespace
		if controller.class.name.split("::").first == "Admin"
			"Admin"
		end
	end

	def admin?	
		controller.class.name.split("::").first == "Admin"
	end

	def markdown(content)
		@markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, space_after_headers: true, fenced_code_blocks: true)
		@markdown.render(content)
	end

	def time(date)
		Time.new - date
	end
end

Rails4/Amilti/app/views/admin/posts/_form.html.erb
<%= simple_form_for [:admin, @post] do |f| %>
	<% if @post.errors.any? %>
		<div class="alert alert-danger">
			<ul>
				<% @post.errors.each do |field, message| %>
					<li><%= "#{field}: #{message}" %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<%= f.input :name, :required => false, :error => false, 
				input_html: { class: 'form-control' } %>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group required">
				<%= f.input :slug, input_html: { class: 'form-control' } %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group required">
				<%= f.association :category, include_blank: false,  
				input_html: {class: 'form-control'} %>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group required">
				<%= f.association :user, label_method: :username, include_blank: false, 
				input_html: {class: 'form-control'} %>
			</div>
		</div>
	</div>
	<div class="form-group">
		<%= f.input :content, as: :text, :required => false, :error => false, 
		input_html: {class: 'form-control', cols: 30, rows: 6} %>
	</div>

	<div class="submit">
		<%= f.submit :class => 'btn btn-primary' %>
	</div>
<% end %>

Rails4/Amilti/app/views/admin/posts/edit.html.erb
<h1>Edit Post</h1>
<p><%= link_to 'Back to posts', admin_posts_path %></p>
<%= render 'form' %>

Rails4/Amilti/app/views/admin/posts/index.html.erb
<% if flash[:message] %>
	<div class="alert alert-success">
		<%= flash[:message] %>
	</div>
<% end %>
<h1>Manage posts</h1>
<%= link_to 'Add a new post', new_admin_post_path, class: "btn btn-primary" %>
<table class="table table-striped">
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Category</th>
			<th>Publication data</th>
			<th>Action</th>
        </tr>
	</thead>
	<tbody>
		<% @posts.each do |post| %>
			<tr>
				<td><%= post.id %></td>
				<td><%= post.name %></td>
				<td><%= post.category.name %></td>
				<td><%= post.created_at.strftime('%d-%m-%Y %H:%M')%></td>
				<td>
					<%= link_to('Edit', edit_admin_post_path(post.id), class: "btn btn-primary") %>
					<%= link_to('Delete', admin_post_path(post.id), 
								:method => :delete, class: "btn btn-danger") 
					%>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= paginate @posts %>

Rails4/Amilti/app/views/admin/posts/new.html.erb
<h1>Add Post</h1>
<p><%= link_to 'Back to posts', admin_posts_path %></p>
<%= render 'form' %>

Rails4/Amilti/app/views/home/commentaires/_form.html.erb
<% if flash[:message] %>
	<div class="alert alert-success">
		<%= flash[:message] %>
	</div>
<% end %>
<%= simple_form_for [:home, comment], url: comments_path  do |f| %>
	<% if comment.errors.any? %>
		<div class="alert alert-danger"><strong>Oh snap !</strong> you did some errors</div>
	<% end %>
	<%= f.hidden_field :post_id, :value => post.id %>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group <%= 'has-error' if comment.errors[:mail].any? %>">
				<%= f.input :mail, :required => false, input_html: { class: 'form-control' } %>
			</div>
		</div>
       <div class="col-md-6">
			<div class="form-group <%= 'has-error' if comment.errors[:username].any? %>">
				<%= f.input :username, :required => false, input_html: { class: 'form-control' } %>
			</div>
		</div>
	</div>
	<div class="form-group <%= 'has-error' if comment.errors[:content].any? %>">
		<%= f.input :content, as: :text, :required => false, 
		input_html: {class: 'form-control', cols: 30, rows: 6} %>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
<% end %>

Rails4/Amilti/app/views/home/commentaires/_list.html.erb
<% cache comments do %>
	<% comments.each do |comment| %>
		<div class="row">

			<div class="col-md-2">
				<img src="http://lorempicsum.com/futurama/100/100/4" width="100%">
			</div>

			<div class="col-md-10">
				<p>
					<strong><%= comment.username %></strong> 
					<%= distance_of_time_in_words_to_now(comment.created_at) %>
				</p>
				<p><%= comment.content %></p>
			</div>

		</div>
	<% end %>
<% end %>

Rails4/Amilti/app/views/home/partials/_categories_list.html.erb
<h4>Categories</h4>
<div class="list-group">
	<% cache categories do %>
		<% categories.each do |category| %>
			<%= link_to(category_path(category), class: "list-group-item") do %>
				<span class="badge"><%= category.posts_count %></span>
				<%= category.name %>
			<% end %>
		<% end %>
	<% end %>
</div>

Rails4/Amilti/app/views/home/partials/_latest_post.erb
<h4>Last posts</h4>
<div class="list-group">
	<% posts.each do |post| %>
		<%= link_to(post.name, post_path(post), :class => "list-group-item") %>
	<% end %>
</div>

Rails4/Amilti/app/views/home/posts/_article.html.erb
<% cache post do %>
	<h1><%= post.name %></h1>
	<%= render :partial => 'home/posts/header', :locals => {
		:post => post
	} %>
	<artcile><%= markdown(post.content).html_safe %></article>

	<hr>

	<section class="comments">
		<h3>Comment this post</h3>
		<%= render :partial => 'home/commentaires/form', :locals => {
			:comment => @comment ? @comment : Comment.new,
			:post => post
		} %>
		<h3><%= post.comments.count %> Commentaires</h3>
		<%= render :partial => 'home/commentaires/list', :locals => {
			:comments => post.comments
		} %>
    </section>
<% end %>

Rails4/Amilti/app/views/home/posts/_header.html.erb
<p>
	<small>
		Category : <%= link_to post.category.name, category_path(post.category) %>,
		by <%= link_to post.user.username , author_path(post.user) %> on 
		<em><%= post.created_at.strftime("%b %dth %Y") %></em>
	</small>
</p>

Rails4/Amilti/app/views/home/posts/_list.html.erb
<% cache posts do %>
	<% posts.each do |post| %>
		<article>
			<h2><%= link_to post.name, post_path(post) %></h2>
			<%= render :partial => 'home/posts/header', :locals => {
				:post => post
			} %>
			<p><%= truncate_html(post.content, length: 150 ) %></p>

			<p class="text-right">
				<%= link_to 'Read more...', post_path(post), class: "btn btn-primary" %>
			</p>
		</article>
	<% end %>
<% end %>

<%= paginate posts %>

Rails4/Amilti/app/views/home/posts/author.html.erb
<% content_for :title, "Post by #{@author.username}" %>
<h1><%= @author.username %></h1>
<%= render :partial => 'list', :locals => {
	:posts => @posts
} %>

Rails4/Amilti/app/views/home/posts/category.html.erb
<% content_for :title, @category.name %>
<h1><%= @category.name %></h1>
<%= render :partial => 'list', :locals => {
	:posts => @posts
} %>

Rails4/Amilti/app/views/home/posts/index.html.erb
<% content_for :title, "blog - home" %>
<h1>Blog</h1>
<p class="lead">Welcome on my blog</p>
<%= render :partial => 'list', :locals => {
	:posts => @posts
} %>

Rails4/Amilti/app/views/home/posts/show.html.erb
<% content_for :title, @post.name %>
<%= render :partial => 'home/posts/article', :locals => {
	:post => @post
} %>

Rails4/Amilti/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "#{namespace} - #{controller.controller_name}::#{controller.action_name}" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'partials/sidebar' %>

	<div class="content">
		<%= yield %>
	</div>

</body>
</html>

Rails4/Amilti/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %></title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render :partial => 'partials/sidebar' %>
		<div class="content">
			<% if @categories && @latest_post %>
				<div class="col-md-4 sidebar">
					<%= render :partial => 'home/partials/categories_list', :locals => {
						:categories => @categories
					} %>

					<%= render :partial => 'home/partials/latest_post', :locals => {
						:posts => @latest_post
					} %>
				</div>
			<% end %>
			<% if controller_name == "sessions" %>
				<%= yield %>
			<% else %>
				<div class="col-md-8">
					<%= yield %>
				</div>
			<% end %>
		</div>
	</body>
</html>

Rails4/Amilti/app/views/partials/_sidebar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<%= link_to "Blog", posts_path, :class => "navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse navbar-ex1-collapse navbar-right">
			<ul class="nav navbar-nav">
				<% if admin? %>
					<li><%= link_to "< back to blog", posts_path %></li>
				<% else %>
					<li><%= link_to "Admin", admin_posts_path %></li>
				<% end %>

				<% if user_signed_in? %>
					<li><%= link_to "Logout", destroy_user_session_path %></li>
				<% end %>
	        </ul>
		</div>
	</div>
</div>