Rails4/Scicasoft/config/routes.rb
Rails4::Application.routes.draw do
  match "/login" => 'user#login', as: :login, via: [:get, :post]
  get "/logout" => 'user#logout', as: :logout

  get '/category/:id' => 'posts#category', as: :category
  get '/author/:id' => 'posts#author', as: :author
  post '/new_comment' => 'posts#add_comment', as: :new_comment

  scope '/admin' do
    get '/' => 'admin#index', as: :admin
    get '/posts/new' => 'posts#new', as: :new_post
    get '/posts/:id/edit' => 'posts#edit', as: :edit_post
  end

  resources :posts

  root 'home#index'

end

Rails4/Scicasoft/app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :posts

  validates :name, presence: true, uniqueness: true
end

Rails4/Scicasoft/app/models/comment.rb
class Comment < ActiveRecord::Base
  include Gravtastic
  gravtastic :mail

  belongs_to :post
  validates :username, presence: true
  validates :mail, presence: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  validates :content, presence: true
end

Rails4/Scicasoft/app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :category
  belongs_to :user
  has_many :comments

  validates :name, presence: true
  validates :content, presence: true
  validates :category, presence: true
  validates :user, presence: true

  after_create :set_post_count
  after_destroy :set_post_count

  def set_post_count
    category.post_count = category.posts.count
    category.save
  end
end

Rails4/Scicasoft/app/models/user.rb
require 'digest/sha1'
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true

  has_many :posts
  before_create :crypter_pass

  def self.authenticate username, password
    user = find_by(username: username)
    return nil if user and user.password != User.crypter(password)
    user
  end

  private

    def crypter_pass
      self.password = User.crypter(password)
    end

    def self.crypter pass
      Digest::MD5.hexdigest("BlogMVC" + pass)
    end
end

Rails4/Scicasoft/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!
  def index
    @posts = Post.all.paginate(page: params[:page], per_page: 5)
  end
end

Rails4/Scicasoft/app/controllers/application_controller.rb
# encoding: utf-8
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method "user_signed_in?", "current_user"

  def authenticate_user!
    unless user_signed_in?
      session[:next_url] = ( request.url || "/" )
      redirect_to login_path
      flash[:erreur] = "Authentifiez vous avant d'accéder à cette page."
    end
  end

  def current_user
    session[:user]
  end

  def user_signed_in?
    session[:user] != nil
  end
end

Rails4/Scicasoft/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order('created_at desc').paginate(page: params[:page], per_page: 5)
  end
end

Rails4/Scicasoft/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show, :index]
  layout "admin", only: [:new, :edit, :create]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.paginate(page: params[:page], per_page: 5)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post      = Post.new(post_params)

    respond_to do |format|
      if @post.save
        flash[:notice] = "Post was successfully created."
        format.html { redirect_to admin_path }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to admin_path, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_url }
      format.json { head :no_content }
    end
  end

  def category
    @category = Category.friendly.find(params[:id])
    @posts = @category.posts.paginate(page: params[:page], per_page: 5)
  end

  def author
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page], per_page: 5)
  end

  def add_comment
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to @comment.post
    else
      @post = @comment.post
      render :show
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit!
    end

    def comment_params
      params.require(:comment).permit!
    end
end

Rails4/Scicasoft/app/controllers/user_controller.rb
# encoding: utf-8
class UserController < ApplicationController
  layout "admin"

  def login
    if params[:username]
      username, password = params[:username], params[:password]
      @user = User.authenticate username, password

      if @user
        session[:user] = @user
        flash[:notice] = "Connecté"

        redirect_to (session[:next_url] || admin_path)
      else
        flash[:error] = "Nom d'utilisateur ou mot de passe incorrect"
      end
    end
  end

  def logout
    session[:user] = nil
    redirect_to root_path
    flash[:notice] = "déconnecté"
  end
end

Rails4/Scicasoft/app/helpers/admin_helper.rb
module AdminHelper
end

Rails4/Scicasoft/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails4/Scicasoft/app/helpers/home_helper.rb
module HomeHelper
end

Rails4/Scicasoft/app/helpers/user_helper.rb
module UserHelper
end

Rails4/Scicasoft/app/views/admin/index.html.erb
<h1>Manage posts</h1>

<p><%= link_to 'Add a new post', new_post_path, class: 'btn btn-primary' %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Category</th>
      <th>Publication date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% for post in @posts %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.name %></td>
        <td><%= post.created_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= post.category.name %></td>
        <td>
          <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-primary' %>
          <%= link_to 'Delete', post, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure ?'} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

Rails4/Scicasoft/app/views/posts/_form.html.erb
<p><%= link_to '< Back to posts', admin_path %></p>

<%= simple_form_for(@post, html: { id: 'PostAdminEditForm', multipart: true }) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger">
      <a class="close" data-dismiss="alert">×</a>
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group required">
        <%= f.input :name, input_html: {class: 'form-control', maxlength: 255} %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group required">

      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.association :category, input_html: {class: 'form-control'} %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.association :user, label: 'Author', label_method: :username, input_html: {class: 'form-control'} %>
      </div>
    </div>
  </div>
  <div class="form-group required">
    <%= f.input :content, as: :text, input_html: {class: 'form-control', cols: 30, rows: 6} %>
  </div>
  <div class="submit">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

Rails4/Scicasoft/app/views/posts/_list.html.erb
<% for post in @posts %>

  <article>
    <h2><%= link_to post.name, post %></h2>
    <p><small>
      Category : <%= link_to post.category.name, category_path(post.category) %>,
      by <%= link_to post.user.username, author_path(post.user) %>, on <em><%= post.created_at.strftime("%b %d %Y") %></em>
    </small></p>
    <p><%= truncate post.content, length: 450 %></p>
    <p class="text-right"><%= link_to 'Read mode...', post, class: 'btn btn-primary' %></p>
  </article>

  <hr>

<% end %>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails, previous_label: '&laquo;', next_label: '&raquo;' %>

Rails4/Scicasoft/app/views/posts/author.html.erb
<% content_for :title do %>
  Author : <%= @user.username %>
<% end %>
<div class="page-header">
  <h1>Blog</h1>
  <p class="lead">Author : <%= @user.username %></p>
</div>

<%= render '/posts/list' %>

Rails4/Scicasoft/app/views/posts/category.html.erb
<% content_for :title do %>
  Category : <%= @category.name %>
<% end %>
<div class="page-header">
  <h1>Blog</h1>
  <p class="lead">Category : <%= @category.name %></p>
</div>

<%= render '/posts/list' %>

Rails4/Scicasoft/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

Rails4/Scicasoft/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

Rails4/Scicasoft/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

Rails4/Scicasoft/app/views/posts/show.html.erb
<% content_for :title do %>
  <%= @post.name %>
<% end %>
<div class="page-header">
  <h1><%= @post.name %></h1>
  <p><small>
  Category : <%= link_to @post.category.name, category_path(@post.category) %>,
  by <%= link_to @post.user.username, author_path(@post.user) %>, on <em><%= @post.created_at.strftime("%b %d %Y") %></em>
  </small></p>
</div>

<article>
  <%= Markdown.new( @post.content ).to_html.html_safe %>
</article>

<hr>

<section class="comments">

  <h3>Comment this post</h3>

  <% if @comment.errors.any? %>
    <div class="alert alert-danger"><strong>Oh snap !</strong> you did some errors</div>
  <% end %>

  <%= simple_form_for @comment, url: new_comment_path do |f| %>
    <%= f.input :post_id, label: false, input_html: {type: :hidden} %>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group <%= 'has-error' if @comment.errors.messages.keys.include? :mail %>">
          <%= f.input :mail, label: false, input_html: {class: 'form-control', type: :email, placeholder: 'Your email'} %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group <%= 'has-error' if @comment.errors.messages.keys.include? :username %>">
          <%= f.input :username, error_html: { class: 'has-error'}, label: false, input_html: {class: 'form-control', placeholder: 'Your username'} %>
        </div>
      </div>
    </div>
    <div class="form-group <%= 'has-error' if @comment.errors.messages.keys.include? :content %>">
      <%= f.input :content, as: :text, error_html: { class: 'has-error'}, label: false, input_html: {class: 'form-control', placeholder: 'Your comment', rows: 3} %>
    </div>
    <div class="form-group">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <h3><%= @post.comments.count %> Commentaires</h3>

  <% for comment in @post.comments %>

    <div class="row">
      <hr>

      <div class="col-md-2">
        <%= image_tag comment.gravatar_url size: 100 %>
      </div>
      <div class="col-md-10">
        <p><strong><%= comment.username %></strong> <%= distance_of_time_in_words_to_now comment.created_at %></p>
        <p><%= comment.content %></p>
      </div>
    </div>

  <% end %>

</section>

Rails4/Scicasoft/app/views/user/login.html.erb
<%= form_tag login_path, class: 'form-signin' do %>
  <h4 class="form-signin-heading">Please sign in</h4>
  <input name="username" type="text" class="form-control" placeholder="Username" autofocus>
  <input name="password" type="password" class="form-control" placeholder="Password">
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
<% end %>

Rails4/Scicasoft/app/views/user/logout.html.erb
<h1>User#logout</h1>
<p>Find me in app/views/user/logout.html.erb</p>